# Generated by Django 5.1.7 on 2025-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_reward_player_coins_player_renombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='games/default_game.png', null=True, upload_to='games'),
        ),
    ]
