# Generated by Django 5.1.7 on 2025-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='games/default_game.webp', null=True, upload_to='games'),
        ),
    ]
