# Generated by Django 5.1.7 on 2025-03-22 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mmr',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
