# Generated by Django 5.1.7 on 2025-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_player_mmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, default='Torneo...', max_length=255, null=True),
        ),
    ]
