# Generated by Django 5.2 on 2025-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tournament_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_player_per_team',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
