# Generated by Django 5.2 on 2025-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_tournament_max_player_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
