# Generated by Django 5.2 on 2025-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_tournament_max_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentteam',
            name='seed',
        ),
    ]
