# Generated by Django 5.2 on 2025-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20250420_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches_generated',
            field=models.BooleanField(default=False),
        ),
    ]
