# Generated by Django 5.2 on 2025-04-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_match_team1_confirmed_match_team1_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
    ]
