# Generated by Django 5.2 on 2025-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_tournament_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
