# Generated by Django 5.2 on 2025-05-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leadered', to='web.player'),
        ),
    ]
