# Generated by Django 5.2 on 2025-05-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='searching_teammates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to='web.player'),
        ),
    ]
