# Generated by Django 6.0.5 on 2026-05-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_team_searching_teammates_alter_team_leader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("tournament_reminder", "Tournament Reminder"),
                            ("match_ready", "Match Ready"),
                            ("match_result", "Match Result"),
                            ("reward", "Reward"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "urgency",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Critical")], default=2
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("send_email", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retries", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.match",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-urgency", "-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="web_notific_status_a73ca1_idx"),
                    models.Index(fields=["urgency"], name="web_notific_urgency_d9cc64_idx"),
                    models.Index(fields=["created_at"], name="web_notific_created_36f637_idx"),
                ],
            },
        ),
    ]
