# Generated by Django 6.0.5 on 2026-05-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
    ]
