# Generated by Django 6.0.5 on 2026-05-12 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_remove_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_users",
            field=models.ManyToManyField(
                blank=True, related_name="notification_recipients", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
